<?php
require(__DIR__.'/../../_common.php');

echo implode(' ', FrequentWordsWithMismatchesAndReverseComplements(
	'CGCTTGACCAACAATTTTCGCATGCAACAATTCAATTCAACAAATGGACCGCGACGACCAAGACGACATGCGCTTCAACGCCGCCGCGACTTCGCATGCGCATGATGATGCGCTTCAACAAGACTTTTCGCTTTTCGCATGCAATTTTGACCAACGCGACCAAGACGACTTTTCAACAAATGCGCATGCGCTTGACTTCAATTCAAATGCGCCGC',
	5,
	2,
	TRUE
));